# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79ec15a0bb2dfd19f552a93d39ad39466dac72872a8f328029d52408ae9983c3bf4673f953b109eb0c6795cfa021816eacaf5a82e8a7998dcc579420f934b99f

test:
  secret_key_base: 76e732831eedb7d76a99aebc6fe1229000128a92d4d168a994b0be9ee899840e6aedeeb2656e060b12a1619b427831b8f172c23c27d9c9801a9d47b729ace31c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
